# Generated by Django 6.0.2 on 2026-02-20 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationresult',
            name='domain',
            field=models.CharField(choices=[('cooking', 'Cooking'), ('assembly', 'Assembly'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='evaluationresult',
            name='document_title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='evaluationresult',
            name='evaluation_data',
            field=models.JSONField(help_text='Stores the step and guide evaluation JSON'),
        ),
    ]
