# Generated by Django 6.0.2 on 2026-02-24 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluator', '0002_evaluationresult_domain_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluationresult',
            name='domain',
            field=models.CharField(choices=[('cooking', 'Cooking'), ('assembly', 'Assembly'), ('learning', 'Learning to use the product'), ('software', 'Software tutorial'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
